name: CI

on:
  push:
    tags: [ "v*" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create-binary-packages:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Get repo files
        uses: actions/checkout@v4
      
      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm
      
      - name: Setup .NET (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: Install WIX (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          dotnet tool install --global wix --version 4.0.0
          wix extension add --global WixToolset.UI.wixext/4.0.4
        shell: bash
      
      - name: Configure
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release
        shell: bash
      
      - name: Build
        run: cmake --build build --config Release
        shell: bash
      
      - name: Create DEB and RPM (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd build
          cpack -G DEB -C Release
          cpack -G RPM -C Release
        shell: bash
      
      - name: Create DMG (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          cd build
          cpack -G DragNDrop -C Release
        shell: bash
      
      - name: Create MSI (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd build
          cpack -G WIX -C Release
        shell: bash
      
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.deb
            build/*.rpm
            build/*.dmg
            build/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
